# Generated by Django 4.2.7 on 2026-01-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(
                blank=True, default=list, help_text="List of image URLs"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_type",
            field=models.CharField(
                choices=[("STORE", "In Store"), ("SHIP", "Shipped")],
                default="SHIP",
                help_text="Fulfillment type: In Store pickup or Shipped",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                default="",
                help_text="External image URL (CDN, S3, vendor URL)",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
                to_field="slug",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="products_pr_product_1b7905_idx"
            ),
        ),
    ]
