# Generated by Django 4.2.7 on 2026-01-04 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("total_customers", models.PositiveIntegerField(default=0)),
                (
                    "avg_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cash_on_delivery",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "card_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mobile_money",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "revenue_snapshots",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="revenue_sna_date_432342_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=200)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_searches",
                "ordering": ["-searched_at"],
                "indexes": [
                    models.Index(fields=["query"], name="user_search_query_bb8ad9_idx"),
                    models.Index(
                        fields=["user"], name="user_search_user_id_f62885_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="user_search_session_6d7fe4_idx"
                    ),
                    models.Index(
                        fields=["searched_at"], name="user_search_searche_ac098e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_product", "View Product"),
                            ("add_to_cart", "Add to Cart"),
                            ("remove_from_cart", "Remove from Cart"),
                            ("checkout_start", "Checkout Start"),
                            ("checkout_complete", "Checkout Complete"),
                            ("search", "Search"),
                            ("login", "Login"),
                            ("register", "Register"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("target_type", models.CharField(blank=True, max_length=20, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_behaviors",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_behavi_user_id_093984_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="user_behavi_session_29f2d3_idx"
                    ),
                    models.Index(
                        fields=["action"], name="user_behavi_action_b8c2d3_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="user_behavi_timesta_f7c28a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_views",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_views",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="product_vie_product_7f94a4_idx"
                    ),
                    models.Index(
                        fields=["user"], name="product_vie_user_id_e5a5c3_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="product_vie_session_8ab555_idx"
                    ),
                    models.Index(
                        fields=["viewed_at"], name="product_vie_viewed__28cb00_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CartAbandonment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("cart_items_count", models.PositiveIntegerField()),
                ("cart_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("abandoned_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("recovered", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cart_abandonments",
                "ordering": ["-abandoned_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="cart_abando_user_id_aa7647_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="cart_abando_session_85931e_idx"
                    ),
                    models.Index(
                        fields=["abandoned_at"], name="cart_abando_abandon_2ba747_idx"
                    ),
                    models.Index(
                        fields=["recovered"], name="cart_abando_recover_b75617_idx"
                    ),
                ],
            },
        ),
    ]
